# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # action命令，安装Node10
    - name: install node
          # 使用action库  actions/setup-node安装node
      uses: actions/setup-node@v1
      with:
          node-version: 12
    # action命令，install && test
    - name: build
        # 运行的命令或者 action
      run: |
          npm install
          npm run build && rm -rf ./node_modules
    - name: deploy
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avz –-exclude=server/db –-exclude=server/mock_db"
        SOURCE: "./"
        REMOTE_HOST: "119.29.101.122"
        REMOTE_USER: "root"
        TARGET: "/var/www/mock"
    - name: start
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: root@119.29.101.122
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
        command: |
          cd /var/www/mock
          cnpm install
          pm2 restart npm || pm2 start npm -- run start:pro
